public class Comentarios {

    //Tener cuidado con el parámetro1 porque debe estar en minúsculas
    //Este método solo debe usarse en caso de...
    public String metodo(String parametro1) {
        String a = ""; //Aquí a representa...
        String b = a.concat("."); //Aquí concateno porque.....
        //Estos pasos no se pueden intercambiar porque entonces...
        return new String();
    }
}
